

services:
  worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: ./manage.sh
    volumes:
      - ../app:/app/app
      - ../manage.sh:/app/manage.sh
      - ../celery_worker:/app/celery_worker
      - ../celery_config.py:/app/celery_config.py
      - ../celery_app.py:/app/celery_app.py
      - ../tasks.py:/app/tasks.py
    environment:
      - ENV=test
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AZURE_BLOB_CONTAINER=experiments
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - AZURE_IMAGE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      

    depends_on:
      - rabbitmq
      - redis
      - azurite

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:latest
    container_name: redisserver
    ports:
      - 6379:6379

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - 10000:10000
